<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="en" sourcelanguage="en">
  <context>
    <name>QtControl</name>
    <message>
      <source>PopWidget_TempUnit</source>
      <translation>Temp.</translation>
    </message>
    <message>
      <source>PopWidget_Lang</source>
      <translation>語系</translation>
    </message>
    <message>
      <source>LANG0</source>
      <translation>英文</translation>
    </message>
    <message>
      <source>LANG1</source>
      <translation>繁體中文</translation>
    </message>
    <message>
      <source>TEMP_Celsius</source>
      <translation>°C</translation>
    </message>
    <message>
      <source>TEMP_Fahrenheit</source>
      <translation>°F</translation>
    </message>
  </context>
  <context>
    <name>popupWidget</name>
    <message>
      <source>LANG0</source>
      <translation>英文</translation>
    </message>
    <message>
      <source>LANG1</source>
      <translation>繁體中文</translation>
    </message>
    <message>
      <source>TEMP_Celsius</source>
      <translation>°C</translation>
    </message>
    <message>
      <source>TEMP_Fahrenheit</source>
      <translation>°F</translation>
    </message>
  </context>
</TS>
